---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mmdebstrap:
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - builder: ubuntu-24.04
          architecture: amd64
          platform: ubuntu
          suite: noble
          mirror: https://mirror.pilotfiber.com/ubuntu
          components: main restricted universe multiverse
        - builder: ubuntu-24.04-arm
          architecture: arm64
          platform: ubuntu
          suite: noble
          mirror: https://mirrors.mit.edu/ubuntu-ports
          components: main restricted universe multiverse
        - builder: ubuntu-24.04
          architecture: amd64
          platform: debian
          suite: bookworm
          mirror: http://deb.debian.org/debian
          components: main contrib non-free non-free-firmware
        - builder: ubuntu-24.04-arm
          architecture: arm64
          platform: debian
          suite: bookworm
          mirror: http://deb.debian.org/debian
          components: main contrib non-free non-free-firmware
    runs-on: ${{ matrix.builder }}
    name: ${{ matrix.platform }}:${{ matrix.suite }}:${{ matrix.architecture }}
    steps:
    - run: echo "force-unsafe-io" | sudo tee /etc/dpkg/dpkg.cfg.d/apt-speed-up
    - run: echo "path-exclude=/usr/share/doc/*" | sudo tee -a /etc/dpkg/dpkg.cfg.d/apt-speed-up
    - run: echo "path-exclude=/usr/share/locale/*" | sudo tee -a /etc/dpkg/dpkg.cfg.d/apt-speed-up
    - run: echo "path-exclude=/usr/share/man/*" | sudo tee -a /etc/dpkg/dpkg.cfg.d/apt-speed-up
    - run: sudo sed -i -E 's@http://azure.archive.ubuntu.com/ubuntu@https://mirror.pilotfiber.com/ubuntu@' /etc/apt/sources.list.d/ubuntu.sources
    - run: sudo sed -i -E 's@http://ports.ubuntu.com/ubuntu-ports@https://mirrors.mit.edu/ubuntu-ports@' /etc/apt/sources.list.d/ubuntu.sources
    - run: cat /etc/apt/sources.list.d/ubuntu.sources
    - run: sudo mount -t tmpfs tmpfs /var/lib/apt/lists
    - run: sudo apt-get update
    - run: >-
        sudo apt-get install -y --no-install-recommends
        mmdebstrap debian-archive-keyring
    - run: sudo mount -t tmpfs tmpfs /tmp
    - run: task
      env:
        MIRROR: '${{ matrix.mirror }}'
        ARCHITECTURE: '${{ matrix.architecture }}'
        PLATFORM: '${{ matrix.platform }}'
        SUITE: '${{ matrix.suite }}'
        COMPONENTS: '${{ matrix.components }}'
    - uses: actions/attest-build-provenance@v2
      with:
        subject-path: ${{ matrix.platform }}-${{ matrix.suite }}-${{ matrix.architecture }}-rootfs.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.suite }}-${{ matrix.architecture }}
        path: ${{ matrix.platform }}-${{ matrix.suite }}-${{ matrix.architecture }}-rootfs.tar.zst
