---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mmdebstrap:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
        - builder: ubuntu-24.04
          architecture: amd64
          platform: ubuntu
          suite: noble
          mirror: https://mirror.pilotfiber.com/ubuntu
          components: main restricted universe multiverse
        - builder: ubuntu-24.04-arm
          architecture: arm64
          platform: ubuntu
          suite: noble
          mirror: https://mirrors.mit.edu/ubuntu-ports
          components: main restricted universe multiverse
        - builder: ubuntu-24.04
          architecture: amd64
          platform: debian
          suite: bookworm
          mirror: http://deb.debian.org/debian
          components: main contrib non-free non-free-firmware
        - builder: ubuntu-24.04-arm
          architecture: arm64
          platform: debian
          suite: bookworm
          mirror: http://deb.debian.org/debian
          components: main contrib non-free non-free-firmware
    runs-on: ${{ matrix.builder }}
    name: ${{ matrix.platform }}:${{ matrix.suite }}:${{ matrix.architecture }}
    steps:
    - run: sudo sed -i -E 's@http://azure.archive.ubuntu.com/ubuntu@https://mirror.pilotfiber.com/ubuntu@' /etc/apt/sources.list.d/ubuntu.sources
    - run: sudo sed -i -E 's@http://ports.ubuntu.com/ubuntu-ports@https://mirrors.mit.edu/ubuntu-ports@' /etc/apt/sources.list.d/ubuntu.sources
    - run: cat /etc/apt/sources.list.d/ubuntu.sources
    - run: sudo apt-get update
    - run: >-
        sudo apt-get install -y --no-install-recommends
        mmdebstrap debian-archive-keyring
    - run: sudo mount -t tmpfs tmpfs /tmp
    - run: >-
        mmdebstrap
        --variant apt
        --components "${{ matrix.components }}"
        --dpkgopt 'path-exclude=/usr/share/man/*'
        --dpkgopt 'path-include=/usr/share/man/man[1-9]/*'
        --dpkgopt 'path-exclude=/usr/share/locale/*'
        --dpkgopt 'path-include=/usr/share/locale/locale.alias'
        --dpkgopt 'path-exclude=/usr/share/doc/*'
        --dpkgopt 'path-include=/usr/share/doc/*/copyright'
        --dpkgopt 'path-include=/usr/share/doc/*/changelog.Debian.*'
        --include 'init,systemd-resolved,systemd-timesyncd,systemd-oomd'
        --include 'libnss-myhostname,libnss-resolve,libnss-systemd,libpam-systemd'
        ${{ matrix.suite }}
        ${{ matrix.platform }}-${{ matrix.suite }}-${{ matrix.architecture }}-rootfs.tar.zst
        ${{ matrix.mirror }}
